# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TrafficSignInventory
                                 A QGIS plugin
 Automated traffic sign inventory from Mapillary detections with MUTCD mapping and export.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-13
        copyright            : (C) 2026 by Raswanth
        email                : raswanth@asu.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TrafficSignInventory class from file TrafficSignInventory.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .traffic_sign_inventory import TrafficSignInventory
    return TrafficSignInventory(iface)
